# Generated by Django 4.1.1 on 2022-10-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
