# Generated by Django 4.1.1 on 2022-10-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='rp',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
