# Generated by Django 4.1.1 on 2022-10-04 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_report_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='boundaries',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='is_localize',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
