# Generated by Django 4.1.1 on 2022-10-04 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_instance_boundaries_instance_is_localize_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('db_status', models.IntegerField(choices=[(-1, 'Deleted'), (0, 'Pending'), (1, 'Active')], default=1)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('id_string', models.CharField(db_index=True, max_length=200)),
                ('desc', models.CharField(blank=True, max_length=260, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='instance',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='instances', to='app.label'),
        ),
    ]
