# Generated by Django 4.1.1 on 2022-10-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_label_instance_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='today_report',
            field=models.IntegerField(default=0),
        ),
    ]
